#整合  datasource 中的连接 4 要素
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.36.41.66:3506/testdb
    username: root
    password: MaYEsT.qTl12G3/@*
  # redis 配置
  redis:
    # 地址
    host: 121.36.41.66
    # 端口，默认为6379
    port: 6389
    # 数据库索引
    database: 3
    # 密码
    password: MaYEsT.qTl12G3/@*
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
# mp 的配置
mybatis-plus:
  configuration:
    #    日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    开启驼峰映射
    map-underscore-to-camel-case: true
    # 扫描的包别名
  type-aliases-package: com.zjw.model
  #  扫描resource下面的xml文件 需要在自己改
  mapper-locations: classpath:/sql/mapper/*Mapper.xml

#  global-config:
#    db-config:
#      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: null # 逻辑已删除值(默认为 null)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)eld:

# 启动类端口号
server:
  port: 8090