spring:
  redis:
    # 地址
    host: 121.36.41.66
    # 端口，默认为6379
    port: 6389
    # 数据库索引
    database: 3
    # 密码
    password: MaYEsT.qTl12G3/@*
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
